### ISSUE TITLE
Modify mysql_tzinfo_to_sql to use session variable wsrep_replicate_myisam

### ISSUE THREAD

**Issue by ronin13** [percona/percona-xtradb-cluster#4]
Based on https://bugs.launchpad.net/percona-xtradb-cluster/+bug/1280270

wsrep_replicate_myisam was not a session variable, hence the error.

Now, that it is, it needs to be added to mysql_tzinfo_to_sql

**Comment by akopytov** [comment]
Moved to JIRA.
